
# This file is auto-generated by the ADK code generator.
# Do not edit this file directly.

from google.adk.agents import LlmAgent
from . import tools

# A dictionary to easily map tool names to their function objects
TOOL_FUNCTION_MAP = {

    "weather-tool": tools.get_weather_report,

}


# Definition for test_agent
test_agent = LlmAgent(
    model="gemini-2.5-flash",
    name="test_agent",
    instruction="""You are a helpful weather assistant.""",
    tools=[
        TOOL_FUNCTION_MAP[tool_ref]
        for tool_ref in ['weather-tool']
    ],
)


# Set the root agent for the application
# For this POC, we'll assume the first agent is the root.
root_agent = test_agent
