
# This file is auto-generated by the ADK code generator.
# Do not edit this file directly.

from google.adk.agents import LlmAgent, SequentialAgent
from google.genai.types import GenerateContentConfig
from . import tools

# --- Model Configurations ---
MODEL_CONFIG_MAP = {

    "gemini-flash-creative": {
        "model": "gemini-2.5-flash",
        
        "generate_content_config": GenerateContentConfig(
            
            temperature=0.7,
            
        ),
        
    },

    "gemini-flash-focused": {
        "model": "gemini-2.5-flash",
        
        "generate_content_config": GenerateContentConfig(
            
            temperature=0.2,
            
        ),
        
    },

}

# --- Tool Mappings ---
TOOL_FUNCTION_MAP = {

}

# --- Agent Definitions ---

# Definition for LlmAgent: idea_generator
idea_generator = LlmAgent(
    name="idea_generator",
    instruction="""You are a creative brainstormer. 
Given a topic from the user, generate a bulleted list of 3-4 key ideas related to it.
""",
    tools=[
        TOOL_FUNCTION_MAP[tool_ref]
        for tool_ref in []
    ],
    output_key="brainstormed_ideas",
    **MODEL_CONFIG_MAP["gemini-flash-creative"]
)

# Definition for LlmAgent: paragraph_writer
paragraph_writer = LlmAgent(
    name="paragraph_writer",
    instruction="""You are a skilled writer. 
Using the following bullet points, write a single, coherent paragraph.

Ideas:
{brainstormed_ideas}
""",
    tools=[
        TOOL_FUNCTION_MAP[tool_ref]
        for tool_ref in []
    ],
    
    **MODEL_CONFIG_MAP["gemini-flash-focused"]
)

# A dictionary to map all agent names to their Python objects
AGENT_OBJECT_MAP = {

    "idea_generator": idea_generator,

    "paragraph_writer": paragraph_writer,


    "writing_pipeline": None, # Placeholder for sequential agents

}

# Definition for SequentialAgent: writing_pipeline
writing_pipeline = SequentialAgent(
    name="writing_pipeline",
    sub_agents=[
        AGENT_OBJECT_MAP[agent_ref]
        for agent_ref in ['idea_generator', 'paragraph_writer']
    ],
)
AGENT_OBJECT_MAP["writing_pipeline"] = writing_pipeline


# --- Set the Root Agent ---
root_agent = AGENT_OBJECT_MAP["writing_pipeline"]